# Generated by Django 5.2 on 2025-04-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_max_students_remove_course_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='completion_date',
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
    ]
