version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./nptel/:/nptel
      - static-data:/nptel/static
    image: nptel:django
    container_name: django_nptel_container
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=django-insecure-z6(gj(g4!f(@5bejr_ut=1cq^)o7)ah=g%@$y*ro)j51$!k-x6
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_NAME=nptel_db
      - DB_USER=postgres_user
      - DB_PASS=Password
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:17.4-alpine3.21
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nptel_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=Password
    container_name: postgres_nptel_db

volumes:
  db-data:
  static-data:
