# Generated by Django 5.2 on 2025-04-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'verbose_name': 'Faculty Profile', 'verbose_name_plural': 'Faculty Profiles'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
    ]
